sudo : required
services:
   - docker

before_install:
   - docker build -t myimage -f Dockerfile.dev .

     #script:
     #   - docker run myimage npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket: "elasticbeanstalk-us-east-1-818728161392"
   bucket-path: "docker-react"
   on:
     branch: master

   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"






